- name: install stuff
  hosts: virtualmachines
  tasks:
    - name: install wget on both vms
      become: yes
      package:
        name: wget
        state: present

    - name: install unzip on vm01
      become: yes
      package:
        name: unzip
        state: present
      when: ansible_host ==  '18.132.18.251'

    - name: install nginx on vm02
      become: yes
      package:
        name: nginx
        state: present
      when: ansible_host == '13.41.227.14'

    - name: uninstall unzip on both vms
      become: yes
      apt:
        name: unzip
        state: absent

# task 2
################### install nginx without nginx ######################
    - name: Install nginx on vm01
      become: yes
      package:
        name: nginx
        state: present
      when: ansible_host == '18.132.18.251'
      register: nginx_install

################### Replace default html with new html stored in ansible ec2 #######################
    - name: Change default nginx file on vm01
      become: yes
      copy:
        src: /var/www/html/index.nginx-debian.html
        dest: /var/www/html/index.nginx-debian.html
      when: ansible_host == '18.132.18.251'

    - name: Restart Nginx
      become: yes
      service:
        name: nginx
        state: restarted
      when: ansible_host == '18.132.18.251'  

################### Pring out the JSON object of installing nginx #######################
    - name: Print out nginx install JSON object 
      debug:  
        var: nginx_install  
      when: ansible_host == '18.132.18.251'


################### install docker on vm01 #######################
    - name: Install prerequisites for Docker repo
      become: yes
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: latest
        update_cache: true
      when: ansible_host == '18.132.18.251'

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      when: ansible_host == '18.132.18.251'

    - name: Add Docker APT repository
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      when: ansible_host == '18.132.18.251'

    - name: Install Docker CE
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        update_cache: yes
      when: ansible_host == '18.132.18.251'

    - name: Install prerequisites for docker-compose
      become: yes
      apt:
        name:
          - python3-pip
          - python3-setuptools
          - virtualenv
      when: ansible_host == '18.132.18.251'

    - name: Install docker-compose
      become: yes
      pip:
        name: docker-compose
      when: ansible_host == '18.132.18.251'

    - name: Ensure Docker is started
      become: yes
      service:
        name: docker
        state: started
      when: ansible_host == '18.132.18.251'

################### install docker on vm02 #######################
    - name: Install Docker on vm02
      become: yes
      shell: curl https://get.docker.com | sudo bash
      when: ansible_host == '13.41.227.14'
